### ISSUE TITLE
2D tools

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1469]
This package  is about updating 2D computational and visualization tools such as slicers, add/sub/mul/div, and other important 2D tools.

**Comment by butlerpd** [comment]
- [ ] this is a test of the task list feature
- [ ] and another task
- [ ] and yet another

**Comment by smk78** [comment]
Is the label name a statement of how good the tools will be, or a comment on the progress to the milestone? :-)

**Comment by butlerpd** [comment]
LOL ... no - I should have commented that this was a test of the zenhub plugin for github.  Actually if you could install the zenhub browser plugin then browse back to this github issue and tell me if you see anything different? Also can you just install the plugin or do you need to create an account? (it is free regardless but am curious how simple it would be.

I realized later how they were handling part of this and that if you don't install the zenhub browser plugin (as opposed to activating the github hooks) this is all you see.  

Otherwise please disregard this issue.

The backstory is that we lost a lot of PM tools when we moved away from trac and I've been trying to research (in my copious free time :-) for things that would work directly in github (ideally trac would do that but it doesn't :-)  zenhub seems to be quite popular and is also "free forever" for open source projects.  It adds things like epics (which are a collection of "stories" also known as issues in github) which as well as dependencies of tickets along with a slew of other things I've not played.   There is the concept of projects in github but that is more of a kanban board thing (which zenhub also enhances on).

**Comment by smk78** [comment]
Was a simple browser plugin for Chrome. Though I did have to give ZinHub access to my GitHub account.

Yes, it looks different!

![image](https://user-images.githubusercontent.com/10938679/75355405-590c1180-58a6-11ea-9bdf-3be8c7de16f4.png)

**Comment by butlerpd** [comment]
Yep that's it. Thanks @smk78

**Comment by butlerpd** [comment]
This was a test of using epics labels with zenhub. It works so will now close this particular ticket
